# Generated by Django 5.1 on 2024-08-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=60, verbose_name='Tent color')),
            ],
        ),
        migrations.CreateModel(
            name='Tent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Tent name')),
                ('price', models.PositiveIntegerField(verbose_name='Tent price')),
                ('material', models.CharField(choices=[('nylon', 'nylon'), ('polyester', 'polyester'), ('canvas', 'canvas'), ('polyethylene', 'polyethylene')], max_length=30, verbose_name='Tent material')),
                ('capacity', models.PositiveIntegerField(verbose_name='Tent capacity (people)')),
                ('weight', models.FloatField(verbose_name='Tent weight (kg)')),
                ('height', models.FloatField(verbose_name='Tent height (m)')),
                ('waterproof_rating', models.PositiveIntegerField(verbose_name='Tent waterproof rating (mm)')),
                ('image1', models.ImageField(upload_to='tent_images', verbose_name='Tent image1')),
                ('image2', models.ImageField(blank=True, upload_to='tent_images', verbose_name='Tent image2')),
                ('image3', models.ImageField(blank=True, upload_to='tent_images', verbose_name='Tent image3')),
                ('color', models.ManyToManyField(related_name='tent_color', to='main.color')),
            ],
        ),
    ]
