# Generated by Django 5.1 on 2024-08-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tent',
            name='waterproof_rating',
        ),
    ]
